### ISSUE TITLE
Undefined is not an object error during initialising

### ISSUE THREAD

**Issue by milon87** [wedoogift/react-native-checkout-payment#1]
<img width="316" alt="Screenshot 2019-09-01 at 1 43 33 AM" src="https://user-images.githubusercontent.com/3435314/64068475-6a0ef980-cc5a-11e9-998d-53467e55cef4.png">

Version: RN 0.60.5

sample code:
`export default class HelloWorldApp extends Component {

  componentDidMount(){
    CheckoutModule.initialize('ck_test_foobar', 'sandbox')
    // or 'live' instead of 'sandbox' for production env.
        .then(() => {
          console.log('Initialization is done.');
        });
  }

  render() {
    return (
        <View style={{ flex: 1, justifyContent: "center", alignItems: "center" }}>
          <Text>Hello, world!</Text>
        </View>
    );
  }
}`

**Comment by victorlevasseur** [comment]
By seing _reactNativeCheckoutPayment.default in your error log, I guess you're importing the module like this : 
`import CheckoutModule from 'react-native-checkout-payment';`

`CheckoutModule` is not a default export but a named export. So (if I'm write about how you wrote your import), it's instead : 
`import { CheckoutModule } from 'react-native-checkout-payment';`

**Comment by victorlevasseur** [comment]
But you're right, the given example in the README is wrong
