### ISSUE TITLE
Null is not an object

### ISSUE THREAD

**Issue by milon87** [wedoogift/react-native-checkout-payment#4]
TypeError: null is not an object (evaluating '_reactNativeCheckoutPayment.CheckoutModeule.initialize')

....

RN version: 62

//Code sample
export default class App extends Component {

    constructor(props) {
        super(props);

        CheckoutModule.initialize('pk', 'sandbox')
        // or 'live' instead of 'sandbox' for production env.
            .then(() => {
                console.log('Initialization is done.');
            });
    }
    render() {
        return (<View style={{flex:1}}>
            <Text>Hello</Text>
        </View>);
    }

}

![Screenshot 2020-06-26 at 9 38 08 PM](https://user-images.githubusercontent.com/3435314/85875995-e6c92080-b7f6-11ea-85d9-44037e2cdc87.png)

**Comment by victorlevasseur** [comment]
Hi, strange error, are you sure the native module is well applied to your build (using Pods ?)?

Can you provide the full code of the App component (with the imports)?

**Comment by milon87** [comment]
I have seen that native module is loaded,
the least support was for iOS 10 and I have updated the pod from 9.0 to 10

<img width="1266" alt="Screenshot 2020-06-26 at 10 21 21 PM" src="https://user-images.githubusercontent.com/3435314/85879003-6ce76600-b7fb-11ea-91d0-5dddd720539a.png">
<img width="652" alt="Screenshot 2020-06-26 at 10 20 29 PM" src="https://user-images.githubusercontent.com/3435314/85878984-6527c180-b7fb-11ea-9b83-60478ae6b75f.png">

**Comment by victorlevasseur** [comment]
The App component might be instanciated before the native modules are loaded. Can you try to put the CheckoutModule.initialize call in the componentDidMount() lifecycle of your component instead of your constructor. We never really tested our code in Class based component (we mainly use function components in our organization).

**Comment by adeel111** [comment]
Facing same issue in function components

  useEffect(() => {
    CheckoutModule.initialize('pk', 'sandbox')
      // or 'live' instead of 'sandbox' for production env.
      .then(() => {
        console.log('Initialization is done.');
      });
  }, []);

How to get rid of this error?

**Comment by github-id01** [comment]
@victorlevasseur Am also facing the same issue upon initialization, just installed the library and used it, is there any post install steps required to get this library working since there's no such indication in the read.md.

By the way am running on Expo 38 on real Android 10 device.

**Comment by victorlevasseur** [comment]
Unfortunately, I don't think this supports Expo projects.
