### ISSUE TITLE
Your API key is invalid

### ISSUE THREAD

**Issue by adeel111** [wedoogift/react-native-checkout-payment#9]
Initialization is done successfully. When I tried to get token by using following piece of code as written in the library description, I got the Error "Your API key is invalid".

CheckoutModule.generateToken({
    card: '4242424242424242',
    name: 'Card Owner',
    expiryMonth: '06',
    expiryYear: '25',
    cvv: '100'
}) // or 'live' for production env.
    .then((result) => {
        console.log('Card token is ' + result.id);
        // See CardTokenisationResponse in index.ts or index.d.ts 
        // to see the data structure of the result.
    })
    .catch((error) => {
        console.warn('Failed because: ' + error.message);
    });

I don't know where to get it and where to place it. There is nothing in the library description. There should be some information about this in the docs. How to get rid of this error?

**Comment by victorlevasseur** [comment]
Are you sure you use the correct token for initializing the library ?
`
CheckoutModule.initialize('ck_test_foobar', 'sandbox') 
    // or 'live' instead of 'sandbox' for production env.
    .then(() => {
        console.log('Initialization is done.');
    });
`

**Comment by adeel111** [comment]
From where to get this token?

**Comment by victorlevasseur** [comment]
You need to get the API key from your checkout.com account that will manage your payments.

**Comment by adeel111** [comment]
I put the key at the place of ck_test_foobar but now I'm getting "Validation error". Why this error?

**Comment by victorlevasseur** [comment]
Where do you get this errror : on initialize or generateToken?

**Comment by adeel111** [comment]
on generateToken.

**Comment by adeel111** [comment]
There was white spaces coming in the card (number) after removing these white spaces I am getting access token successfully.

Thanks for precious response.
